# fly.toml app configuration file generated for algoritmogenetico-patient-shadow-7969 on 2023-11-20T23:02:26-06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "algoritmogenetico-patient-shadow-7969"
primary_region = "gdl"

[build]

[http_service]
  internal_port = 5000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
